---
title: "Bayesian Lasso"
output: Bayesian_Lasso
---

```{r}
n.folds <- 5
n.folds.hyperparameter <- 10
```
```{r}

# - load packages
library('raster')
library('spatial')
library('glmnet')
library('lmtest')
library('reshape')
library("dplyr")
library("grpreg")
library("caret")
library("parallel") # for parallel computing?
library("blockCV") # spatial crossvalidation
library("shiny")
library("rgdal")
library("sf")
library("ggplot2")
library("data.table")
library("stringr")
library(MBSGS)
library("pastecs")
library(kableExtra)
library(matrixStats)
```
```{r}

rbindx <- function(..., dfs=list(...)) {
  ns <- unique(unlist(sapply(dfs, names)))
  do.call(rbind, lapply(dfs, function(x) {
    for(n in ns[! ns %in% names(x)]) {x[[n]] <- NA}; x }))
}

mode <- function(x) { # thanks to https://stackoverflow.com/questions/2547402/how-to-find-the-statistical-mode
  ux <- unique(x)
  tab <- tabulate(match(x, ux))
  ux[tab == max(tab)]
}

Site <- "Val_Priora"

current_dir <- "/Users/beni/Documents/BayianLasso/data/data/src/fixed_sample_points"
data_dir <- file.path(current_dir, "out")
out_dir <- file.path(current_dir, "out", "lasso_fixed")
path <- file.path(data_dir, str_interp("${Site}_geo_df.feather"))
lsl <- arrow::read_feather(path)

lsl$aspect_factor <- lsl$aspect

lsl$aspect_factor[lsl$aspect <= 22.5] <- "N"
lsl$aspect_factor[lsl$aspect > 337.5] <- "N"
lsl$aspect_factor[lsl$aspect > 22.5 & lsl$aspect <= 67.5] <- "NE"
lsl$aspect_factor[lsl$aspect > 67.5 & lsl$aspect <= 112.5] <- "E"
lsl$aspect_factor[lsl$aspect > 112.5 & lsl$aspect <= 157.5] <- "SE"
lsl$aspect_factor[lsl$aspect > 157.5 & lsl$aspect <= 202.5] <- "S"
lsl$aspect_factor[lsl$aspect > 202.5 & lsl$aspect <= 247.5] <- "SW"
lsl$aspect_factor[lsl$aspect > 247.5 & lsl$aspect <= 292.5] <- "W"
lsl$aspect_factor[lsl$aspect > 292.5 & lsl$aspect <= 337.5] <- "NW"
lsl$aspect_factor <- as.factor(lsl$aspect_factor)

lsl$lslpts <- lsl$landslide

lsl$gesteinsklasse <- as.factor(lsl$gesteinsklasse)

label <- c('lslpts')
numeric_features <- c(
  'elevation',
  'slope',
  'curvature_plan',
  'curvature_profile',
  'roughness',
  'flowacc',
  'twi',  # Topographic wetness index
  'distance_to_roads',
  'distance_to_streams',
  'density_roads',
  'density_streams',
  'flowdir',
  'max_precip_5Y',
  'max_precip_10Y',
  'stack_precip_5Y',
  'stack_precip_10Y',
  'snow_days',
  'snow_cover_days',
  'grow_season_length',
  'frost_ch_freq'
)
features <- c(
  numeric_features,
  'gesteinsklasse',
  'aspect_factor'
)

lsl <- subset(lsl, select = c(label, 'x', 'y', features))

lsl <- lsl %>% mutate_at(numeric_features, scale)

lsl

```
```{r}

# Remove NaN values from data frame

print(str_interp("NaN values before: ${sum(is.na(lsl))}"))

if ("Lockergesteine" %in% unique(lsl$gesteinsklasse)) {
  lsl$gesteinsklasse[is.na(lsl$gesteinsklasse)] <- "Lockergesteine"
} else {
  lsl$gesteinsklasse[is.na(lsl$gesteinsklasse)] <- "Sedimentgesteine"
}
lsl$aspect_factor[is.na(lsl$aspect_factor)] <- "E"

lsl[is.na(lsl)] <- 0

print(str_interp("NaN values after: ${sum(is.na(lsl))}"))

```
```{r}

one_hot_encode_factors <- function(lsl) {
    # One Hot Encoded (dummy variables) factor features
    options(na.action="na.fail")
    lsl_ohe <- model.matrix(~ ., data = lsl)[, -1]  # -1 removes intercept

    return (lsl_ohe)
}

remove_coordinates <- function(data) {
    x <- subset(data, select=-c(x, y))
    return(x)
}

split_label <- function(data) {
    return(list(
      x=subset(data, select=-c(lslpts)),
      y=as.numeric(data$lslpts)
    ))
}

preprocess <- function(x) {
    return(x %>% one_hot_encode_factors %>% remove_coordinates)
}

calc_groups <- function(x) {
    # - define groups: dummy coding of a factor is treated as group
    # - alternative
    # - find factors
    l.covar <- features
    l.factors <- names(lsl[l.covar])[t.f <- unlist(lapply(lsl[l.covar], is.factor))]
    l.numeric <- names(t.f[!t.f])
    # create a vector that labels the groups with the same number
    groups <- c(
      1:length(l.numeric),
      unlist(
        sapply(1:(length(l.factors)), function(n) {
          rep(n + length(l.numeric), nlevels(lsl[[l.factors[n]]])-1)
        })
      )
    )
    return(groups)
}

# One Hot Encoded (dummy variables) factor features
options(na.action="na.fail")
lsl_ohe <- model.matrix(lslpts ~ ., data = lsl)[, -1]  # -1 removes intercept

# Split features and target variable
res <- split_label(lsl)
x <- res$x
y <- res$y
x <- preprocess(x)

groups <- calc_groups(x)

cat(str_interp("dim(x):         ${dim(x)[1]}, ${dim(x)[2]}"), sep="\n")
cat(str_interp("length(y):      ${length(y)}"), sep="\n")
cat(str_interp("length(groups): ${length(groups)}"), sep="\n")

print(aggregate(data.frame(count = y), list(value = y), length))
print(as.data.frame(x))
```
```{r}

coefs.boot <- vector()

k.boot <- 20
n.folds <- 5

# Needed for raster
elevation <- raster(str_interp("/Users/beni/Documents/BayianLasso/data/data/Explanatory_Variables_Datasets/Elevation/DEM_2m_${Site}.tif"))
pa_data <- sf::st_as_sf(lsl, coords = c("x", "y"), crs = raster::crs(elevation))

for (j in 1:k.boot) {

    set.seed(j)
    print(j)

    # spatial blocking by specified range and random assignment
    sb1 <- spatialBlock(speciesData = pa_data,
                        species = "lslpts",
                        theRange = 1000,
                        rasterLayer = elevation,
                        k = n.folds,
                        selection = "random",
                        iteration = 10,
                        showBlocks = FALSE)
    cvID <- sb1$foldID
    # - merge data together with ID subset
    lsl.data.ID <- cbind(lsl, cvID)
    for (i in 1:n.folds) {
        lsl.data.train <- subset(lsl.data.ID, cvID != i, select = -c(cvID))
        lsl.data.test <- subset(lsl.data.ID, cvID == i, select = -c(cvID))

        res <- split_label(lsl.data.train)
        x.train <- preprocess(res$x)
        y.train <- res$y

        groups <- calc_groups(x)

        fit.grpreg <- cv.grpreg(
            X = x.train,
            y = y.train,
            group = groups,
            penalty = "grLasso",
            family = "binomial",
            nfolds = n.folds.hyperparameter,
            nlambda = 100,
            alpha = 1, # alpha=1 => No l2-regularization
            returnY = TRUE
        )

        # - choose optimal lambda: CV minimum error + 1 SE (see glmnet)
        l.se <- fit.grpreg$cve[fit.grpreg$min] + fit.grpreg$cvse[fit.grpreg$min]

        idx.se <- min(which(fit.grpreg$cve < l.se))
        lambda.min <- fit.grpreg$lambda.min
        # - get the non-zero coefficients:
        #coeffiecients.glmnet <- coef(glmnet.glmnet, s=lambda.min)
        coef.grpreg <- fit.grpreg$fit$beta[, idx.se]

        coefs.boot.row <- data.frame(t(coef.grpreg))
        colnames(coefs.boot.row) <- names(coef.grpreg)
        coefs.boot.df <- rbindx(coefs.boot.row, if(exists("coefs.boot.df")) coefs.boot.df)
    }
}

print(coefs.boot.df)
```

```{r}
coef_frequentist <- coefs.boot.df
```
```{r}

# X = x,
# y = y,
# group = groups,
# #penalty="grLasso",
# penalty = "grLasso",
# family = "binomial",
# nfolds = n.folds.hyperparameter,
# nlambda = 100,
# alpha = 1, # alpha=1 => No l2-regularization
# returnY = TRUE

old_g <- -1
group_size <- integer()
for (g in groups) {
    if (g == old_g) {
        group_size[[g]] <- group_size[[g]] + 1
    } else {
        group_size[g] <- 1
    }
    old_g <- g
}

res <- BGLSS(
    y,
    x,
    niter = 10000,
    burnin = 5000,
    group_size = group_size,
    a = 1,
    b = 1,
    num_update = 100,
    niter.update = 100,
    verbose = FALSE,
    alpha = 0.1,
    gamma = 0.1,
    pi_prior = TRUE,
    pi = 0.5,
    update_tau = TRUE,
    option.weight.group = FALSE,
    option.update = "global",
    lambda2_update = NULL
)

print(res)
```

```{r}
print(dim(res$coef))
```

```{r}

data <- t(res$coef)
colnames(data) <- colnames(x)

data <- data.frame(data)

ggplot(stack(data), aes(x = ind, y = values)) +
    geom_boxplot() +
    ggtitle(Site) +
    scale_x_discrete(guide = guide_axis(angle = 90))

```
```{r}

data <- coef_frequentist[, -1]

ggplot(stack(data), aes(x = ind, y = values)) +
    geom_boxplot() +
    ggtitle(Site) +
    scale_x_discrete(guide = guide_axis(angle = 90))

```